# Generated by Django 3.1.2 on 2021-06-02 08:39

import django.core.validators
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('round_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='round')),
                ('game_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('score2', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(default='tt tournament', max_length=50)),
                ('image', models.ImageField(default='dummy/tournament.jpg', upload_to='tournament/images')),
                ('start_date', models.DateField()),
                ('registration_end', models.DateField()),
                ('Max_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('end_date', models.DateField(null=True)),
                ('total_players', models.CharField(choices=[('2', '2'), ('4', '4'), ('8', '8'), ('16', '16'), ('32', '32'), ('64', '64')], default='2', max_length=10)),
                ('status', models.CharField(blank=True, default='upcoming', max_length=8)),
                ('match_type', django_mysql.models.ListCharField(models.CharField(choices=[("Men's single", "Men's single"), ("Men's double", "Men's double"), ("Women's single", "Women's single"), ("Women's double", "Women's double"), ('Mixed single', 'Mixed single'), ('mixed double', 'mixed double')], max_length=14, null=True), max_length=120, null=True, size=6)),
                ('winner', django_mysql.models.ListCharField(models.IntegerField(null=True), max_length=30, null=True, size=3)),
            ],
        ),
    ]
